let prod = [
    {
      "id": 1,
      "title": "The Silent Patient",
      "author": "Alex Michaelides",
      "subtitle": "A Psychological Thriller",
      "button": "Buy Now",
      "url": "https://example.com/the-silent-patient",
      "image": "https://via.placeholder.com/150", 
      "price": "499",
      "currency": "INR",
      "category": "Fiction"
    },
    {
      "id": 2,
      "title": "Educated",
      "author": "Tara Westover",
      "subtitle": "A Memoir",
      "button": "Buy Now",
      "url": "https://example.com/educated",
      "image": "https://via.placeholder.com/150",
      "price": "599",
      "currency": "INR",
      "category": "Non-Fiction"
    },
    {
      "id": 3,
      "title": "The Alchemist",
      "author": "Paulo Coelho",
      "subtitle": "A Novel",
      "button": "Buy Now",
      "url": "https://example.com/the-alchemist",
      "image": "https://via.placeholder.com/150",
      "price": "399",
      "currency": "INR",
      "category": "Fiction"
    },
    {
      "id": 4,
      "title": "The Power of Habit",
      "author": "Charles Duhigg",
      "subtitle": "Why We Do What We Do in Life and Business",
      "button": "Buy Now",
      "url": "https://example.com/the-power-of-habit",
      "image": "https://via.placeholder.com/150",
      "price": "450",
      "currency": "INR",
      "category": "Non-Fiction"
    },
    {
      "id": 5,
      "title": "Harry Potter and the Sorcerer's Stone",
      "author": "J.K. Rowling",
      "subtitle": "Book 1 of the Harry Potter Series",
      "button": "Buy Now",
      "url": "https://example.com/harry-potter-1",
      "image": "https://via.placeholder.com/150",
      "price": "699",
      "currency": "INR",
      "category": "Children's Books"
    },
    {
      "id": 6,
      "title": "The 7 Habits of Highly Effective People",
      "author": "Stephen R. Covey",
      "subtitle": "Powerful Lessons in Personal Change",
      "button": "Buy Now",
      "url": "https://example.com/7-habits",
      "image": "https://via.placeholder.com/150",
      "price": "550",
      "currency": "INR",
      "category": "Self-Help"
    },
    {
      "id": 7,
      "title": "The Great Gatsby",
      "author": "F. Scott Fitzgerald",
      "subtitle": "A Novel",
      "button": "Buy Now",
      "url": "https://example.com/the-great-gatsby",
      "image": "https://via.placeholder.com/150",
      "price": "399",
      "currency": "INR",
      "category": "Fiction"
    },
    {
      "id": 8,
      "title": "Becoming",
      "author": "Michelle Obama",
      "subtitle": "A Memoir",
      "button": "Buy Now",
      "url": "https://example.com/becoming",
      "image": "https://via.placeholder.com/150",
      "price": "799",
      "currency": "INR",
      "category": "Non-Fiction"
    },
    {
      "id": 9,
      "title": "The Catcher in the Rye",
      "author": "J.D. Salinger",
      "subtitle": "A Novel",
      "button": "Buy Now",
      "url": "https://example.com/the-catcher-in-the-rye",
      "image": "https://via.placeholder.com/150",
      "price": "450",
      "currency": "INR",
      "category": "Fiction"
    },
    {
      "id": 10,
      "title": "Sapiens: A Brief History of Humankind",
      "author": "Yuval Noah Harari",
      "subtitle": "A Non-Fiction Book",
      "button": "Buy Now",
      "url": "https://example.com/sapiens",
      "image": "https://via.placeholder.com/150",
      "price": "699",
      "currency": "INR",
      "category": "Non-Fiction"
    },
    {
      "id": 11,
      "title": "The Subtle Art of Not Giving a F*ck",
      "author": "Mark Manson",
      "subtitle": "A Counterintuitive Approach to Living a Good Life",
      "button": "Buy Now",
      "url": "https://example.com/subtle-art",
      "image": "https://via.placeholder.com/150",
      "price": "499",
      "currency": "INR",
      "category": "Self-Help"
    },
    {
      "id": 12,
      "title": "The Diary of a Young Girl",
      "author": "Anne Frank",
      "subtitle": "The Definitive Edition",
      "button": "Buy Now",
      "url": "https://example.com/diary-of-a-young-girl",
      "image": "https://via.placeholder.com/150",
      "price": "399",
      "currency": "INR",
      "category": "Non-Fiction"
    },
    {
      "id": 13,
      "title": "The Fault in Our Stars",
      "author": "John Green",
      "subtitle": "A Novel",
      "button": "Buy Now",
      "url": "https://example.com/the-fault-in-our-stars",
      "image": "https://via.placeholder.com/150",
      "price": "499",
      "currency": "INR",
      "category": "Fiction"
    },
    {
      "id": 14,
      "title": "The Book Thief",
      "author": "Markus Zusak",
      "subtitle": "A Novel",
      "button": "Buy Now",
      "url": "https://example.com/the-book-thief",
      "image": "https://via.placeholder.com/150",
      "price": "599",
      "currency": "INR",
      "category": "Fiction"
    },
    {
      "id": 15,
      "title": "The Art of War",
      "author": "Sun Tzu",
      "subtitle": "An Ancient Chinese Military Treatise",
      "button": "Buy Now",
      "url": "https://example.com/the-art-of-war",
      "image": "https://via.placeholder.com/150",
      "price": "299",
      "currency": "INR",
      "category": "Exam Books"
    },
    {
      "id": 16,
      "title": "The Hitchhiker's Guide to the Galaxy",
      "author": "Douglas Adams",
      "subtitle": "A Science Fiction Classic",
      "button": "Buy Now",
      "url": "https://example.com/hitchhikers-guide",
      "image": "https://via.placeholder.com/150",
      "price": "399",
      "currency": "INR",
      "category": "Fiction"
    },
    {
      "id": 17,
      "title": "The Immortal Life of Henrietta Lacks",
      "author": "Rebecca Skloot",
      "subtitle": "The Story of a Woman Who Changed Medicine",
      "button": "Buy Now",
      "url": "https://example.com/immortal-life",
      "image": "https://via.placeholder.com/150",
      "price": "499",
      "currency": "INR",
      "category": "Non-Fiction"
    },
    {
      "id": 18,
      "title": "The Little Prince",
      "author": "Antoine de Saint-Exupéry",
      "subtitle": "A Novella",
      "button": "Buy Now",
      "url": "https://example.com/the-little-prince",
      "image": "https://via.placeholder.com/150",
      "price": "350",
      "currency": "INR",
      "category": "Children's Books"
    },
    {
      "id": 19,
      "title": "The Kite Runner",
      "author": "Khaled Hosseini",
      "subtitle": "A Novel",
      "button": "Buy Now",
      "url": "https://example.com/the-kite-runner",
      "image": "https://via.placeholder.com/150",
      "price": "499",
      "currency": "INR",
      "category": "Fiction"
    },
    {
      "id": 20,
      "title": "The Book of Joy",
      "author": "Dalai Lama & Desmond Tutu",
      "subtitle": "Lasting Happiness in a Changing World",
      "button": "Buy Now",
      " url": "https://example.com/book-of-joy",
      "image": "https://via.placeholder.com/150",
      "price": "599",
      "currency": "INR",
      "category": "Non-Fiction"
    },
    {
      "id": 21,
      "title": "The Chronicles of Narnia",
      "author": "C.S. Lewis",
      "subtitle": "The Complete Chronicles",
      "button": "Buy Now",
      "url": "https://example.com/narnia",
      "image": "https://via.placeholder.com/150",
      "price": "799",
      "currency": "INR",
      "category": "Children's Books"
    },
    {
      "id": 22,
      "title": "The 48 Laws of Power",
      "author": "Robert Greene",
      "subtitle": "Master the Game of Life",
      "button": "Buy Now",
      "url": "https://example.com/48-laws",
      "image": "https://via.placeholder.com/150",
      "price": "699",
      "currency": "INR",
      "category": "Self-Help"
    },
    {
      "id": 23,
      "title": "The Road",
      "author": "Cormac McCarthy",
      "subtitle": "A Novel",
      "button": "Buy Now",
      "url": "https://example.com/the-road",
      "image": "https://via.placeholder.com/150",
      "price": "450",
      "currency": "INR",
      "category": "Fiction"
    },
    {
      "id": 24,
      "title": "The Girl on the Train",
      "author": "Paula Hawkins",
      "subtitle": "A Novel",
      "button": "Buy Now",
      "url": "https://example.com/girl-on-the-train",
      "image": "https://via.placeholder.com/150",
      "price": "499",
      "currency": "INR",
      "category": "Fiction"
    },
    {
      "id": 25,
      "title": "The Art of Happiness",
      "author": "Dalai Lama",
      "subtitle": "A Handbook for Living",
      "button": "Buy Now",
      "url": "https://example.com/art-of-happiness",
      "image": "https://via.placeholder.com/150",
      "price": "399",
      "currency": "INR",
      "category": "Self-Help"
    },
    {
      "id": 26,
      "title": "The Secret",
      "author": "Rhonda Byrne",
      "subtitle": "The Power of Positive Thinking",
      "button": "Buy Now",
      "url": "https://example.com/the-secret",
      "image": "https://via.placeholder.com/150",
      "price": "499",
      "currency": "INR",
      "category": "Self-Help"
    },
    {
      "id": 27,
      "title": "The Little Book of Hygge",
      "author": "Meik Wiking",
      "subtitle": "The Danish Way to Live Well",
      "button": "Buy Now",
      "url": "https://example.com/little-book-of-hygge",
      "image": "https://via.placeholder.com/150",
      "price": "399",
      "currency": "INR",
      "category": "Non-Fiction"
    },
    {
      "id": 28,
      "title": "The Night Circus",
      "author": "Erin Morgenstern",
      "subtitle": "A Novel",
      "button": "Buy Now",
      "url": "https://example.com/night-circus",
      "image": "https://via.placeholder.com/150",
      "price": "599",
      "currency": "INR",
      "category": "Fiction"
    },
    {
      "id": 29,
      "title": "The 5 AM Club",
      "author": "Robin Sharma",
      "subtitle": "Own Your Morning, Elevate Your Life",
      "button": "Buy Now",
      "url": "https://example.com/5-am-club",
      "image": "https://via.placeholder.com/150",
      "price": "499",
      "currency": "INR",
      "category": "Self-Help"
    },
    {
      "id": 30,
      "title": "The Book of Life",
      "author": "Jiddu Krishnamurti",
      "subtitle": "A Guide to Understanding Yourself",
      "button": "Buy Now",
      "url": " https://example.com/book-of-life",
      "image": "https://via.placeholder.com/150",
      "price": "599",
      "currency": "INR",
      "category": "Philosophy"
    }
  ]